// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyComponent: typeof import('./src/components/MyComponent.vue')['default']
    MyDialog: typeof import('./src/components/MyDialog.vue')['default']
    MyDisclosure: typeof import('./src/components/MyDisclosure.vue')['default']
    MyForm: typeof import('./src/components/MyForm.vue')['default']
    MyListbox: typeof import('./src/components/MyListbox.vue')['default']
    MyMenuButton: typeof import('./src/components/MyMenuButton.vue')['default']
    MyPopover: typeof import('./src/components/MyPopover.vue')['default']
    MyRadioGroup: typeof import('./src/components/MyRadioGroup.vue')['default']
    MyToggle: typeof import('./src/components/MyToggle.vue')['default']
  }
}

export { }
